name: First-Workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: centos-latest
    steps:
      - name: Install httpd
        run: |
          sudo yum update -y
          sudo yum install httpd -y
          
      - name: copy web pages
        run: echo "hello httpd" > /var/www/html/index.html

      - name: Start services
        run: |
          sudo systemctl start httpd
          sudo systemctl enabled httpd
          
      



     

    
  
