name: First-Workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Apache
        run: |
          sudo apt update -y
          sudo apt-get install apache2 -y
          
      - name: copy web pages
        run: echo "hello apache2" > /var/www/html/index.html

      - name: Start services
        run: |
          sudo systemctl start apache2
          sudo systemctl enabled apache2
          
      



     

    
  
