name: First-Workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: My new message
        run: echo "Hello from github action"
        
     



     

    
  
