name: Docker CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.riteshmehar397@gmail.com}}
          password: ${{secrets.dockerhub@12345}}
          
      - name: docker build and push
        uses: docker/build-push-action@v6
          
        

      
  
  


